name: Build and Push

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 1 * *"

jobs:
  docker:
    strategy:
      matrix:
        version: [3.8, 3.9, latest]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ${{ matrix.version }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PYTHON_VERSION=${{ matrix.version }}
          push: true
          tags: lukewiwa/aws-lambda-python-sqlite:${{ matrix.version }}


