name: Build and Push

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 0 1 * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push 3.9
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PYTHON_VERSION=3.9
          push: true
          tags: lukewiwa/aws-lambda-python-sqlite:latest,lukewiwa/aws-lambda-python-sqlite:3.9

      - name: Build and push 3.8
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PYTHON_VERSION=3.8
          push: true
          tags: lukewiwa/aws-lambda-python-sqlite:3.8

